---
- name: Molecule tests
  hosts: all
  become: true

  vars:

  pre_tasks:
    - name: PRE-TASK update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
        autoremove: true
        autoclean: true
      changed_when: false
      when: ansible_os_family == 'Debian'

  roles:
    - role: basictheprogram.nsswitch
